## BCIS 5110 - Assignment 7
Q1: 3 points each sub-question. Q2: 9 points

### 1. Manipulate arrays
The purpose of the assignment is to work with n-dimensional arrays.

1.1 Create a 5X4 array with random integer between 1 and 100. The required arguments of the creation function to do this is np.random.randint(low, high, size). As usual, low is inclusive and high is exclusive. 

In [1]:
from numpy import random

random_array1=random.randint(1,101, size=(5,4))
print("\nGenerated 5X4 array is as shown below: \n")
print(random_array1)


Generated 5X4 array is as shown below: 

[[10 81 97 47]
 [46 40 94 95]
 [10 39 86 35]
 [54 96 56 86]
 [56 49 80 34]]


1.2 Change the element of second row/third column to 0

In [8]:
random_array1[1][2]=0
print(random_array1)

[[34 73 54 45]
 [57 98  0 74]
 [97  3 62 59]
 [71 75 69 48]
 [ 2 72 54  4]]


1.3 Create a slice of two rows and three columns (row 2 and 3, column 2-4). Your way of creation should guarantee that changing the slice will not change the original array. Change the element at row 2 and column 2 in the slice to 100. Print the slice before and after change.

In [9]:
print(random_array1[1:3, 1:4])
random_array1[2][2]=5
print(random_array1[1:3, 1:4])

[[98  0 74]
 [ 3 62 59]]
[[98  0 74]
 [ 3  5 59]]


1.4 Create a two-dimensional array with 5 integers in one row. You can create it your own way. <br>
Can this array and the one created in 1.1 be added together?

In [5]:
array_l = [[1,2, 3,4, 5],
        [0,0,0,0,0],
        [0,0,0,0,0]]

print("\nNewly created 2D array of dimention 3X5\n")
for o in array_l:
    print(o)


Newly created 2D array of dimention 3X5

[1, 2, 3, 4, 5]
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]


1.5 Following 1.4, how can we make the two arrays add together?

In [7]:
from numpy import random

#gerenating array with random number
array_m=random.randint(1,101, size=(5,4))
#printing array
print("\nfirst Random array Created  : \n")
print(array_m)

array_n=random.randint(1,101, size=(5,4))
#printing array
print("\nSecond Random array generated to add: \n")
print(array_n)

sum_1 = [[0,0,0,0],
        [0,0,0,0],
        [0,0,0,0],
        [0,0,0,0],
        [0,0,0,0]]

# iterate through rows
for a in range(len(sum_1)):  
# iterate through columns
    for b in range(len(sum_1[0])):
        sum_1[a][b] = array_m[a][b] + array_n[a][b]

print("\nSum of arrays : \n")
for o in sum_1:
    print(o)


first Random array Created  : 

[[  2  53  55  43]
 [ 12  54   5  38]
 [ 61  43  35  55]
 [ 22  12  79  53]
 [ 70 100  21  63]]

Second Random array generated to add: 

[[71 27 93  2]
 [56  8  8 53]
 [ 7 25 67 91]
 [ 2  3 27 71]
 [59 53 12 53]]

Sum of arrays : 

[73, 80, 148, 45]
[68, 62, 13, 91]
[68, 68, 102, 146]
[24, 15, 106, 124]
[129, 153, 33, 116]


1.6 Multiply the elements (in the 5X4 array created in 1.1) that are divisable by 3 with 2.

In [3]:
from numpy import random

#gerenating array with random number
array_r=random.randint(1,101, size=(5,4))
#printing array
print("\nArray Created in step 1.1 : \n")
print(array_r)


# iterate through rows
for a in range(len(array_r)):  
# iterate through columns
    for b in range(len(array_r[0])):
        if(array_r[a][b] % 3 == 0):
            array_r[a][b] = array_r[a][b] * 2

print("\nArray After the operation : \n")
for c in array_r:
    print(c)


Array Created in step 1.1 : 

[[ 64  71  32  33]
 [ 47  93  24  51]
 [ 19  77  89  83]
 [ 37  62 100  56]
 [ 11  17  72  93]]

Array After the operation : 

[64 71 32 66]
[ 47 186  48 102]
[19 77 89 83]
[ 37  62 100  56]
[ 11  17 144 186]


1.7 Calculate the mean and the standard deviation of each column using aggregation functions of the array from 1.1. Use the mean and std to get the standardized value of each element using the formula: (x - mean)/std, where x is the element. Tips: Which axis should we use?

In [2]:
from numpy import random
import statistics 


array_p=random.randint(1,101, size=(5,4))
print("\nArray Created in step 1.1 : \n")
print(array_p)
print("\n")

array_q = [[0,0,0,0],
        [0,0,0,0],
        [0,0,0,0],
        [0,0,0,0],
        [0,0,0,0]]

for var_x in range(len(array_p)):  
    mean=statistics.mean(array_p[var_x])
    stdev=statistics.stdev(array_p[var_x])
    print("Row ",var_x," : Mean -> ",mean," , Standard deviation -> ",stdev)
    for var_y in range(len(array_p[var_x])): 
        array_q[var_x][var_y]=( array_p[var_x][var_y] -mean ) / stdev

print("\nStandardized value of each elements : \n")
for var_z in array_q:
    print(var_z)


Array Created in step 1.1 : 

[[58 16 43 15]
 [27 66 30 18]
 [50 94 94 12]
 [98 12 90 22]
 [26 81 50 37]]


Row  0  : Mean ->  33  , Standard deviation ->  21.118712081942874
Row  1  : Mean ->  35  , Standard deviation ->  21.118712081942874
Row  2  : Mean ->  62  , Standard deviation ->  39.534794801541594
Row  3  : Mean ->  55  , Standard deviation ->  44.75488800120049
Row  4  : Mean ->  48  , Standard deviation ->  23.769728648009426

Standardized value of each elements : 

[1.1837843095259462, -0.8049733304776433, 0.47351372381037843, -0.8523247028586811]
[-0.37881097904830274, 1.467892543812173, -0.23675686190518921, -0.8049733304776433]
[-0.3035300944456168, 0.8094135851883114, 0.8094135851883114, -1.2647087268567367]
[0.9607889086628165, -0.9607889086628165, 0.7820374837953157, -0.7373496275784406]
[-0.9255469562056767, 1.3883204343085151, 0.08414063238233425, -0.46277347810283836]


### 2. Write a Python function to implement a simple encryption technique.<br>

In this encryption, each letter in the plaintext is replaced by a letter some fixed number of positions down the alphabet. For example, with a left shift of 3, D would be replaced by A, E would become B, and so on. <br>
Your function takes two arguments, the original words and the number of steps to shift (Left shift negative and right shift positive).

Sample input: 'apple', -3<br>
Output with left shift of 3: 'xmmib'

You may define the alphabet as a list. Each letter has its position.
Left shift of 3 means index - 3 and right shift means index + 3.

Tip: How can you make sure the index is between 0-25? Negative index can also be used.


In [1]:
plain_txt = "abcdefghijklmnopqrstuvwxyz"
org_strng = input("Enter string: ")
new_strng = ""
caesar_shft = int(input("Enter shift: "))
for var1 in range(0,len(org_strng)):
  position = plain_txt.index(org_strng[var1])
  new_position = (position + caesar_shft) % 26
  new_strng += plain_txt[new_position]

print(new_strng)

Enter string: apple
Enter shift: -3
xmmib


In [ ]:
Preeti Chaudhry